apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ include "snippetquiz-frontend-chart.fullname" . }}
  name: {{ include "snippetquiz-frontend-chart.fullname" . }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ include "snippetquiz-frontend-chart.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "snippetquiz-frontend-chart.fullname" . }}
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: snippetquiz-frontend
          image: ghcr.io/rafaesc/snippetquiz/snippetquiz-frontend:{{ .Chart.AppVersion }}
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: {{ include "snippetquiz-frontend-chart.fullname" . }}-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ include "snippetquiz-frontend-chart.fullname" . }}
  name: {{ include "snippetquiz-frontend-chart.fullname" . }}
spec:
  selector:
    app: {{ include "snippetquiz-frontend-chart.fullname" . }}
  ports:
    - port: 3000
      targetPort: 3000