services:
  db:
    build: ./infra/postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: snippetquiz
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRESQL_USER} -d ${POSTGRESQL_DATABASE}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass redispass
    volumes:
      - ./local/cache:/data

  broker:
    image: apache/kafka:4.0.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,DOCKER://:29092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,DOCKER://broker:29092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 1

<<<<<<< HEAD
  init-kafka:
    image: apache/kafka:4.0.0
    depends_on:
      - broker
    volumes:
      - ./infra/broker/entrypoint.sh:/entrypoint.sh
    command: [ "/entrypoint.sh" ]

=======
  # ai-processor:
  #   build:
  #     context: ./backend
  #     dockerfile: python/Dockerfile.dev
  #   container_name: snippetquiz-ai-processor
  #   ports:
  #     - "50051:50051"
  #   environment:
  #     AI_GENERATION_SERVICE_PORT: 50051
  #     AI_GENERATION_SERVICE_HOST: "0.0.0.0"
  #     KAFKA_HOST: "broker"
  #     KAFKA_PORT: "29092"
  #     CORE_SERVICE_HOST: "host.docker.internal"
  #     CORE_SERVICE_PORT: "7001"
  #   depends_on:
  #     - broker
  #   volumes:
  #     - ./backend/python:/usr/src/app
  #     - ./backend/protos:/usr/src/backend/protos
  
>>>>>>> 363c56c (feat: core service and ai processor event driven)
  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    restart: unless-stopped
    ports:
      - '9000:9000'
    environment:
      KAFKA_BROKERCONNECT: 'broker:29092'
      JVM_OPTS: '-Xms32M -Xmx64M'
      SERVER_SERVLET_CONTEXTPATH: '/'
    depends_on:
      init-kafka:
        condition: service_completed_successfully

networks:
  default:
    name: snippetquiz
