apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: snippetquiz-api-gateway-chart
  namespace: snippetquiz
spec:
  values:
    redis:
      host: "redis-sessions.snippetquiz.svc.cluster.local"
      port: "6379"
    
    routers:
      aiContentServiceHost: "snippetquiz-ai-content-service-chart"
      authServiceHost: "snippetquiz-auth-service-chart"
      coreServiceHost: "snippetquiz-core-service-chart"
