apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: snippetquiz-core-service-chart
  namespace: snippetquiz
spec:
  values:
    redis:
      host: "redis-sessions.snippetquiz.svc.cluster.local"
      port: "6379"
    
    kafka:
      host: "snippetquiz-kafka-kafka-bootstrap.svc.cluster.local"
      port: "9092"
