apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: snippetquiz-auth-service-chart
  namespace: snippetquiz
spec:
  values:
    redis:
      host: "redis-sessions.snippetquiz.svc.cluster.local"
      port: "6379"
    
    frontend:
      url: "https://sq.rafaescala.com"
    
    kafka:
      host: "snippetquiz-kafka-kafka-bootstrap"
      port: "9092"
