apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/namespace.yaml
  - secret-env.yaml
  - secret-ghcr.yaml
  - ai-content-service
  - api-gateway
  - auth-service
  - core-service
  - frontend
