apiVersion: v1
data:
    api-base-url: ENC[AES256_GCM,data:/4KdoJWGvA/7eyGOQFcTgHmE9rsVJfIq+pSKJw==,iv:BDWAA2wh6M9h4SSF6y8JIn1+vrci7mxoLmEpWPn6z6c=,tag:XFIQnWHfO/3vxT5rKfFo7w==,type:str]
    cookie-secret: ENC[AES256_GCM,data:J6DdSOaVvVEMv9fyeP9ts39LdQTLI8zN+wPg0A==,iv:R9Fm3zXdgr2fsByz8t/QNuv0h8jWTgV934nsoemN9/4=,tag:fxbC+BiO2terfF6d+wHDEw==,type:str]
    email-password: ENC[AES256_GCM,data:GVxJgWqD+nnGa9eSXN83DQLpGgnNaGtN13zK8Q==,iv:jORHOG6aOr5tt+C99jPq4UEADV5B0Tuxkv04ZPYz8hE=,tag:qj3UKBljrAoGkZtzBA35Qw==,type:str]
    email-username: ENC[AES256_GCM,data:lGl4ONb8c9sDBun8EPNMdvBonGMpHlE/braS7cjEiSvcferA,iv:zR4/eMahWc7BBQXpMCH4fbjczdQwI5POEFiJbJWzK7g=,tag:CXzrIRkt/9ggDcgT1QWZJA==,type:str]
    jwt-auth-expires-in: ENC[AES256_GCM,data:S/QOqmqRphE=,iv:1bGFPfiygeijC4PCj+Q3WreizPPqy3NHRCGo4ulxIBs=,tag:owNCAcnbU7j3PGhCJ7qwxA==,type:str]
    jwt-auth-refresh-expires-in: ENC[AES256_GCM,data:XpBG4Yrukrk=,iv:MTUXSKNFOloO3T7n23KaQTQFfb++ERUcoV6k6uD+pZw=,tag:ynn1SMpIVN8VZI/Z15AUag==,type:str]
    jwt-auth-refresh-secret: ENC[AES256_GCM,data:g0cJCsvBb5uhejEQw6/W+kb3E/+Eu71FqxSxcT+KExNrC7/t,iv:XTtk+EhK1YOqONykredO0v+3Wd9ykEAhzEhJyxfD+PQ=,tag:7XWF9XSKKgZCsngR1lVGGQ==,type:str]
    jwt-auth-secret: ENC[AES256_GCM,data:NIYutrk1Fj0vbWrL0n+6p7hBU0nTCPHH,iv:DDXKb6weSMEuvRNB+e5PPScWOoLDBMJ2HTw3saTXW0Q=,tag:tncKaH1oCQUf01ATTkQ0cw==,type:str]
    jwt-auth-verification-expires-in: ENC[AES256_GCM,data:JxzS/5T3YH8=,iv:uHcbeYRb2Ys3iuTLrWaf/SmlmjLBMtXg8liZbbUCjAc=,tag:hDEjt1GBJjoQHMlEy5Ojsw==,type:str]
    jwt-auth-verification-secret: ENC[AES256_GCM,data:+f9SE9apRB5fDQAlBV1s9xAlaMTAXfpKbpkkbumyenj6s/iCzkmrzA==,iv:3lvBMQEcU+nwp5PrsrPMP1Pz29bIqOs9Uz1S24WyvqI=,tag:SHBjgXWfbC/buQETbu1H0A==,type:str]
    openrouter-api-key: ENC[AES256_GCM,data:tIHa0z668vNuHUayNPozbi/r1uQbk1c3Zs5qXgbaquPdQT3SRYL2AYvO5ZCW9Gt5s1aPyJTdF1vyouAveyN2sa2n4rPjh33puvwmRwJ0u2kCfx9vsZ9+nBJ2meODS2xJXx+HvA==,iv:GlW7vwiFYY2nN1+iHLhTWAKL7qcLMQ+BgZPpFhU0UcA=,tag:Qp9mSCP49rHW+QeNsI2XyA==,type:str]
kind: Secret
metadata:
    name: common-env
    namespace: snippetquiz
sops:
    age:
        - recipient: age1744p6gzjcmysmyx4lmlmhre9sxqysp68er0ywwahgaqm8q98nd0s6r797v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOc3RHODRXNWVyMTBwWnps
            V2hWZ290WHEzL0VXQlJSL0dWREQ4eUs0MERJCnJ1d1FNTzNGd1BtTzhqWC9VVlQ3
            NlBnbEcrRWpUamJZcmRMZFhzUDVLMG8KLS0tIFY4YU1GSisrNHBsY3NYQjViRTVO
            QlhUbXBlY1Y4YUY2dlJ1ZHpEZGduSm8KDb/7T2/hVA0+e/uZl4oIkcwxhp7Q0c7b
            LxTqeQPILy5iSBPUajJuliKSjTkbtIV5Ho7bCyJS4KrzBLyQsMpnDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T02:08:04Z"
    mac: ENC[AES256_GCM,data:HxlP3O7CTXdpaD5pqRJp4Jgu+KKNkfr4UTPeSahWqRPxcGCzL4Apt2x3sXk+3S6z9lKiQT1NKhKNdfFC7JJ7ZADjSrGnLbCtsASx/H4m1G9pnTTDT3gJ5E7fzOxL4t1PEOcSgzz9QlE1VC/ap36O5FMyQ4ep4OmDKjbuglc9vl8=,iv:eh/eAGbmeiKs9eD5oDYLp3NboZm3RMPK3jvLyAqjkUs=,tag:Y5V2/DnIM26/WhU/f9+S7w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
