apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
type: Opaque
data:
  POSTGRESQL_USER: {{ include "helpers.postgresql.user" . | b64enc }}
  POSTGRESQL_PASSWORD: {{ include "helpers.postgresql.password" . | b64enc }}
  REDIS_PASSWORD: {{ .Values.redis.password | b64enc }}

  JWT_AUTH_EXPIRES_IN: {{ .Values.jwt.authExpiresIn | b64enc }}
  JWT_AUTH_REFRESH_EXPIRES_IN: {{ .Values.jwt.authRefreshExpiresIn | b64enc }}
  JWT_AUTH_REFRESH_SECRET: {{ .Values.jwt.authRefreshSecret | b64enc }}
  JWT_AUTH_SECRET: {{ .Values.jwt.authSecret | b64enc }}
  JWT_AUTH_VERIFICATION_EXPIRES_IN: {{ .Values.jwt.authVerificationExpiresIn | b64enc }}
  JWT_AUTH_VERIFICATION_SECRET: {{ .Values.jwt.authVerificationSecret | b64enc }}

  EMAIL_USERNAME: {{ .Values.emailService.username | b64enc }}
  EMAIL_PASSWORD: {{ .Values.emailService.password | b64enc }}
  COOKIE_SECRET: {{ .Values.cookies.secret | b64enc }}

  FRONTEND_URL: {{ .Values.frontend.url | b64enc }}
