replicaCount: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

postgresql:
  host: postgres
  port: "5432"
  database: snippetquiz
  user: snippetquiz
  password: snippetquiz
  jdbcUri: null

redis:
  host: redis
  port: "6379"
  password: snippetquiz

kafka:
  host: kafka
  port: "9092"

jwt:
  authExpiresIn: null
  authRefreshExpiresIn: null
  authRefreshSecret: null
  authSecret: null
  authVerificationExpiresIn: null
  authVerificationSecret: null

emailService:
  username: null
  password: null

cookies:
  secret: null

frontend:
  url: null