apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:M4A6M7jK3HSsGi+zrrWwJG2ZhSU48l46j8cvteYtUVS6V55WM1GasslBWdRICGwFqAc/4DZTdQocYOCcn3iCkJPAdQir76o6xfRVsBWLowDcbYEeg/erwXCTf+B03P13Ibfh6EVnJuU6iHRPTD8GX6ZZnLqf5R8DG4G3XCWk3e0iAx39bdh7geToMd1CA+2p0Zb1DmaSOJVZDXmD2t6ecTdhdD5MDaEVZMFbxYBL7kJDo5cbW4T0ptnBZEHBLzPauuiLPSTexcAMeRmNycnWXr2q2ZRj+EF7tSX3llebJtAmOBpZ0VjUyg==,iv:1btoGIZ3NqSdLM0hv2lAJHj2fOgqJBfr6uFMy8O6TMs=,tag:bPRGq+koJfFqGXEeVjE4hg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: ghcr-secret
    namespace: flux-system
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age1744p6gzjcmysmyx4lmlmhre9sxqysp68er0ywwahgaqm8q98nd0s6r797v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJUG1vdHluSkR6UTBuQUFK
            YytMWkJkaE1pMlcwZzJuUU1ZMlhmRE1FclM0CnBBSTR2UThSMXRnV1ArUDdGZ3N0
            c3dVdEhkbmVxT2xPZnRhMlcyVWFxNjQKLS0tIDJjRFpSS1lVZWQ4Y0RwTVVqOGZS
            SW5EUjlMY3pDaDFGZjdwZ0I5V2ZaRzgKA1LMtPfcPpVsqKmuRsekLXIIepqD0q7l
            Pq3cAD9Coc38c1gj2blRnIdSj9BvZeUzUkgir7Egi9FaeMGDCcfe1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-20T06:10:54Z"
    mac: ENC[AES256_GCM,data:zZ20hWpmVF4cnCw5xzS9gWQ5YFex3cW4zLIq70vizLhHEX+o85/7JnvBqCvSno/BV24WGp2yUOtfbW7S1N+3rdHTSkYOQmj2S89NA5GxiY71VAVNtQAIraNRNZXJ4wuI1dv69Y36cqBbWmvWL421yzM3sZuENGZemMVUmtocSFU=,iv:m5/+GCQTnUU5LPnOXDNtbyz/nSLV+Wuxyvi1n5OH+cM=,tag:mTPipIl+8+gRbUtkCquYDg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
