apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:2761PEjBCZIzqFqbNGyAydJwoiVW2kZwVX3Vj/BY6lmhyapFiyd1eebUAJSIFOSfavYOTbHOCjNQoWsqhH6B+JxFx5dJE6FoNqzjaFpCNr7yOX0tZsB3Hn0AwgBUqVqlgXG7STUvd1AUXpNA4H5pSHC5I5jgU7qxuDGQewrvsTUzsxamW2KGDF0ty9fU4enwUqt7AjJMan5ZjBSEz7dgA2APD92OjEqgRnE3ePFnvTkoVTaWgZEw/tt4TxrXSxPc/hTWbqymrjV9yEUS2aKJqDkp4f2xDY15McszRIQaKXIFo2QQ2MZeSw==,iv:eR/G1keTPUmqBd0sSc/l521Q9N6jwawSiBlH0W1jELs=,tag:QwSRyEZlXEZhDphLQpS/Qg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: ghcr-secret
    namespace: flux-system
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age1744p6gzjcmysmyx4lmlmhre9sxqysp68er0ywwahgaqm8q98nd0s6r797v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeklQdzBtTnFMUnlFWU1a
            VjZTTksvZndscnBTWHVRYXg0bFdMMW82cFhJCnVTcXdnZDE3Q0NwTHBnaThiTXAw
            SVltZmpKNEJzTWNHOG9zbHphZkJxVmMKLS0tIFMwSUtNMUlPR01BOUIvMDNzQWNE
            SU5IRWxKeVA2eVpQdzJNRWFBQmJFNTgK1Qr/yNZ20viVRQgJGlJ9l9jO6CyCf4xi
            nGTvU07jqzWbQ4qYveJWlD+XXwPKE6rjZY/zQKowBMf9sCyJAJFajA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-18T06:31:57Z"
    mac: ENC[AES256_GCM,data:nIOKNYdjbhw70KdfHIwooYbt02JP6VH5Zq2vDG87b+1mmyKLAZAqfop8VNNZIB2Nd1cbgQ/assB2Js7ZP1pAe4TfyKDsQt1+CEWIR8RWfwV2b+HiZuVKeBBdAAXDrNOxkTGIQzGP7Hpzi1BTx/nsjXqSpTtTb9bKLHl4/8MgF2k=,iv:yyHZIhgUyhZC9xl2GnHSrRRy7HmwmZ8DMIv5jKPKhvU=,tag:iGkdF433uG91EDwt3+Sj2w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
