apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  POSTGRESQL_HOST: {{ include "helpers.postgresql.host" . | quote }}
  POSTGRESQL_PORT: {{ include "helpers.postgresql.port" . | quote }}
  POSTGRESQL_DATABASE: {{ include "helpers.postgresql.database" . | quote }}

  KAFKA_HOST: {{ .Values.kafka.host | quote }}
  KAFKA_PORT: {{ .Values.kafka.port | quote }}
