apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
type: Opaque
data:
  POSTGRESQL_USER: {{ include "helpers.postgresql.user" . | b64enc }}
  POSTGRESQL_PASSWORD: {{ include "helpers.postgresql.password" . | b64enc }}

  OPENROUTER_API_KEY: {{ .Values.openrouter.apiKey | b64enc }}
