apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: snippetquiz-core-service-chart
  namespace: kube-system
spec:
  interval: 5m
  url: oci://ghcr.io/rafaesc/charts/snippetquiz-core-service-chart
  ref:
    tag: 0.0.17
  secretRef:
    name: ghcr-secret
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: snippetquiz-core-service-chart
  namespace: kube-system
spec:
  chartRef:
    kind: OCIRepository
    name: snippetquiz-core-service-chart
    namespace: kube-system
  interval: 10m
  values:
    replicaCount: 1
