apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: snippetquiz-frontend-chart
  namespace: flux-system
spec:
  interval: 5m
  url: oci://ghcr.io/rafaesc/charts/snippetquiz-frontend-chart
  ref:
    tag: 0.0.11
  secretRef:
    name: ghcr-secret
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: snippetquiz-frontend-chart
  namespace: flux-system
spec:
  chartRef:
    kind: OCIRepository
    name: snippetquiz-frontend-chart
    namespace: flux-system
  interval: 10m
  values:
    replicaCount: 1
