apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ai-content-service
  name: ai-content-service
  namespace: snippetquiz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-content-service
  template:
    metadata:
      labels:
        app: ai-content-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - image: ghcr.io/rafaesc/snippetquiz/snippetquiz-ai-content-service:latest
          name: snippetquiz-ai-content-service
          envFrom:
            - secretRef:
                name: common-env
          ports:
            - containerPort: 3004
