apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: frontend-ingressroute-certificate
  namespace: snippetquiz
spec:
  secretName: frontend-certificates-secret
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - sq.rafaescala.com