apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: frontend
  namespace: snippetquiz
spec:
  entryPoints:
    - websecure
    - web
  routes:
    - match: Host(`sq.rafaescala.com`)
      kind: Rule
      services:
        - name: frontend
          port: 3000
  tls:
    secretName: frontend-certificates-secret