apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: snippetquiz-frontend-chart
  namespace: snippetquiz
spec:
  values:
    logLevel: debug

    api:
      url: "http://core-service:3003"
