apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: snippetquiz-frontend-chart
  namespace: flux-system
spec:
  chartRef:
    kind: OCIRepository
    name: snippetquiz
    namespace: flux-system
  interval: 10m
  values:
    replicaCount: 1