apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
 name: flux-system
 namespace: flux-system
resources:
- gotk-components.yaml
- gotk-sync.yaml
- secret-env.yaml
- secret-ghcr.yaml
- ../../../apps/base/frontend
- ../../../apps/base/core-service
- ../../../apps/base/api-gateway
- ../../../apps/base/auth-service
- ../../../apps/base/ai-content-service

