apiVersion: v1
data:
    AI_CONTENT_SERVICE_HOST: ENC[AES256_GCM,data:byvloNJ1luY6a6pLjTsBdsqGv9q53diSCJ1f2Q==,iv:u2pq+HGLMu0j4yzOKaNRNNa2jlb4mS1h5P2E0juJF8A=,tag:zhnncWHmwXePyHUfY1u7kg==,type:str]
    API_BASE_URL: ENC[AES256_GCM,data:j/xOlRB+dFDwCV9oK/wvDCdezgZF5lxnn52uvg==,iv:G5viRNkxxgo1ESFLBRB2cdjFU+YIo1d8BUV/rndKO+g=,tag:gbUXrZRvE1cCD9R0WY3s3g==,type:str]
    AUTH_SERVICE_HOST: ENC[AES256_GCM,data:6DR1qgu7V0Kr+L9hAk4Gtr6MAsw=,iv:M7JVScWU79EZyorSgyvdmINvl4bfgHeCOYNfNGxHrQA=,tag:sjDAry2oA6MbuBYGuUyNQw==,type:str]
    COOKIE_SECRET: ENC[AES256_GCM,data:qtPwEdHN/rkUIL+AkWgIKiVnUMPJ2+OO+BU1hg==,iv:8lqgT9a3G2sJEbianhZFaIPKl2pEP0b/YufY6TTVAws=,tag:7/6MVbn1vHlw5cAPFuT3vg==,type:str]
    CORE_SERVICE_HOST: ENC[AES256_GCM,data:671z3NUr4i67R2G39AMSn04zlnk=,iv:o7CYpBGIgEs50ICiG/U7xK1oVrWuhshVylDhuuD3C9Y=,tag:0UYCsu0z3O+QaK1r+PU3XQ==,type:str]
    EMAIL_PASSWORD: ENC[AES256_GCM,data:1VCAvWWzOv8slLWm6qAc6NSu2Ce+RtKClLNO7Q==,iv:LBMM5JwHDMhkADYLFLEas9aRi+hlIpp5OnSsAV7zUwM=,tag:lTLw2TKCLZ3DIZbzm9K6VQ==,type:str]
    EMAIL_USERNAME: ENC[AES256_GCM,data:yUgYAITC+JJSW8Mjc0QITDav5WRPU/fznsQ0krAojD6WHgJE,iv:8QOZCSJnQEsfvJ6/6A6TWdXKHT6nG+vISqb2haBmUUw=,tag:LbHf4jq36qFWyiVt+i+lWw==,type:str]
    JWT_AUTH_EXPIRES_IN: ENC[AES256_GCM,data:sk8aT9RT+30=,iv:dSek5cs5Bx3EIbvlbvDjWz2MoaOZwdU7A7fip0+Bkhk=,tag:zEOhSlYUiLVp/tQeLsDwHQ==,type:str]
    JWT_AUTH_REFRESH_EXPIRES_IN: ENC[AES256_GCM,data:fn2MiBOej+M=,iv:HN2qjFtgsRBSzdTzfbp4WYMJvoLOvS9eBgzR10NTEe4=,tag:lH0Ql32+MCrdXuOqyU9p3A==,type:str]
    JWT_AUTH_REFRESH_SECRET: ENC[AES256_GCM,data:VBa20sZFhyPBa2uEZFDiFZdcEHpblJhwFRcp5ZqjsrgdL3iM,iv:Uftf3ALRLnObMOqP8vyiRftpu+SW+m8Si42ICB2+mWY=,tag:oXjhlxvDkIE68VhNCHWHlg==,type:str]
    JWT_AUTH_SECRET: ENC[AES256_GCM,data:D3GT1WHihhkkoTW57s0oEIEwXSv/JM4X,iv:3Ab40j1sEprw51XlOKuKrbYGAngg5HaEmROLC5L5BJ4=,tag:FaBXhO0LkKpHt7z87sDWtw==,type:str]
    JWT_AUTH_VERIFICATION_EXPIRES_IN: ENC[AES256_GCM,data:nu9/UvA97Rs=,iv:Oavkj+rqi60PIW5Ap4HTT5ISJkmbBjSUAUSLm92UG1U=,tag:3ugO+iheyVL4zEJj/LYqJw==,type:str]
    JWT_AUTH_VERIFICATION_SECRET: ENC[AES256_GCM,data:JbiAAtoxO4GqwRwgV2GzrTMtubusVT+eQgw7Rs5A5Lr6LkE+mX8FTw==,iv:BAgfVXtel+hkEUzpyHQJ/F10LxNTfkTl+ReP6Gh8eJo=,tag:+0USLzCTm7r9miVuoGbfAQ==,type:str]
    KAFKA_HOST: ENC[AES256_GCM,data:yGYX5gLlyWoY6Jip,iv:MeufhwA3Xc9AxEeXjgGLgmwwbiLRrssxeqNXQVY0kGg=,tag:DjywiiEbhr9Zx4sBwdYRwQ==,type:str]
    KAFKA_PORT: ENC[AES256_GCM,data:wq5uoVQdYNImVoA+,iv:F265WrOeaTycDZFpWNpjbISjc48fKDXc2ZgoVoJhTBY=,tag:Z4xosUUik3WS5oDfOUvofQ==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:kMwmnvJXIdQV8bvkFpvILw9jj+6tDcYXUcCO3fFkhh1uL2U3oDPyD7FS0I5/LKfri1l/HGKa7350fFOjRvoGjMvQknnjHQbpvd2Gf2JcJSLICc0gBISkwH4+nf7y44qv92j0bA==,iv:8exMBuWVMZSIV5xG8JQVoFHj4f9xEJnjiBzoqdhH6i0=,tag:TDAQz0JB6eWgH7fKL2OyfQ==,type:str]
    POSTGRESQL_DATABASE: ENC[AES256_GCM,data:1+AW2saPqUJltk7rFDj/2w==,iv:mr+jBPVZdJA48w6SUajJPXwPCWK1iqKHWICgTqn3ncM=,tag:UQp5K7bZ+MiofFCNj7cpoA==,type:str]
    POSTGRESQL_HOST: ENC[AES256_GCM,data:YJTI1g==,iv:9KnkJeMAvofPS+dE5Q9cHmP+jk0xoFqJeDLEQsMiP9U=,tag:BIRkegO4iVXWdIwGkrdmkw==,type:str]
    POSTGRESQL_PASSWORD: ENC[AES256_GCM,data:QS5l7LZMrEY=,iv:mJQUHymaee2JP7vL5kSquGWTZQc13MmJDJWOejD3AV0=,tag:cb2/i7ID7DejvMSCb6VXQw==,type:str]
    POSTGRESQL_PORT: ENC[AES256_GCM,data:6Tmb0qkTU8g=,iv:fZqPGIwjudUEFkRfOFJRd3gA+lEH6eSKfD+v/UY7L2Q=,tag:pZ1CDB6xWJ6bL8lgxLwOag==,type:str]
    POSTGRESQL_USER: ENC[AES256_GCM,data:d4PNTl4ChTM=,iv:vAqS8+aAh8vs/+dYHWmBbY3Do5lqGYIlTlSB2UgPdso=,tag:WLNGj9XrA3zvNjYLa2IdqQ==,type:str]
    REDIS_HOST: ENC[AES256_GCM,data:Ib01WOQ/zkw=,iv:MpTS/9kMyqiV5mUhxip1LB+StDZIc4K0zFVW7jhXy9o=,tag:7vHzjiR6r5WMwVNrCKEUPw==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:uaf/CGoJW1a+9Srm,iv:J4cxAuhf8epEFRyghI1DzrUR2gFq+X5svx28bD6QnyQ=,tag:YJ0UC18/eQGY1DDioqjYrw==,type:str]
    REDIS_PORT: ENC[AES256_GCM,data:Ls2ucE5IZyQ=,iv:ZNit9WU7hbHkmz3PU74FPIg77CIakszErask9nfHSX0=,tag:/CijDra11GJARuLXHQ8XiA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: common-env
    namespace: flux-system
sops:
    age:
        - recipient: age1744p6gzjcmysmyx4lmlmhre9sxqysp68er0ywwahgaqm8q98nd0s6r797v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3T2xKMWNLZEd1SUhheURU
            ejNiWk9WSEZLSXBkai9nU00zOXMycHVCT1ZrCkJzZmphaXdVTEE4cllPamJhNXVk
            TCs0b0R6cjdkOXQ5aXNSRmZUbjZIcmsKLS0tIGdsdHRKVlZ2MktSZHAyTUpKSXdI
            MFZPS1RmaC82RTQ3MmVXeFJiSGtUUEEKFp/O4zXIlJdFxmpHic9EeZxTvVuhWc+2
            JPDpTUrANblLvnPXGn7W8S1Vc0a8adE3KpgorEegeMgiZj5eHnlOIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-20T04:26:49Z"
    mac: ENC[AES256_GCM,data:hACPU97hMbgUvgTo2YcUdbOWdjW6GARxKETT1u8j14keAdFWWY3zzn8xg2iGLhn9N97C9kSqHkStBvAiKu72i45Cw6ts+yH6C4Yg1ahqNXSxVS1boTF7P8NsXJOJzhSDiYhRk114Yn0+btVKwMSESsuqFOlEZA4vWnvAPrnbTSs=,iv:HaEUri5JMNbY0gFlafCu43Fze02XBQLzhFco6bR2KVg=,tag:0RdLhZIdj43UiDaF09D52g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
