apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: snippetquiz-api-gateway-chart
  namespace: snippetquiz
spec:
  interval: 5m
  url: oci://ghcr.io/rafaesc/charts/snippetquiz-api-gateway-chart
  ref:
    tag: 0.0.22
  secretRef:
    name: ghcr-secret
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: snippetquiz-api-gateway-chart
  namespace: snippetquiz
spec:
  chartRef:
    kind: OCIRepository
    name: snippetquiz-api-gateway-chart
    namespace: snippetquiz
  interval: 10m
  values:
    replicaCount: 1
    
    redis:
      host: ""
      port: ""
      password: ""
    jwt:
      authExpiresIn: ""
      authRefreshExpiresIn: ""
      authRefreshSecret: ""
      authSecret: ""
      authVerificationExpiresIn: ""
      authVerificationSecret: ""

    emailService:
      username: ""
      password: ""

    routers:
      aiContentServiceHost: ""
      authServiceHost: ""
      coreServiceHost: ""

    cookies:
      secret: ""