apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-controllers
  namespace: flux-system
spec:
  interval: 10m
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./deploy/monitoring/controllers/homelab

  decryption:
    provider: sops
    secretRef:
      name: sops-age
#---
#apiVersion: kustomize.toolkit.fluxcd.io/v1
#kind: Kustomization
#metadata:
#  name: monitoring-configs
#  namespace: flux-system
#spec:
#  interval: 10m
#  prune: true
#  sourceRef:
#    kind: GitRepository
#    name: flux-system
#  path: ./deploy/monitoring/configs/homelab
#
#  decryption:
#    provider: sops
#    secretRef:
#      name: sops-age
#  dependsOn:
#    - name: flux-system
#