apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:gtjd/vOr8ikeDgOn27Cen0bFm3tyz5S7MCQxnU0Smrg3OpH/dRAHo8YD8WaFj0RInF3Udij6UqRMnjyDrCo/v4rxWkBPKb38dnq0OnXfnz0GRxLzcOiuoRbICkEAd2Z7cZnwVCEuX9iqIk1IQabKKUnHNTVBTS8P+QKdyBuOa87vOKGUXczwBE5Gn21q95egMZqEIPmmOrMZLzJ5ZThGQv0oV17kDnVvbz6At6QGp2gq21q6WPyz2eXRBGN0Dj0ZZMGNV79XBjvkrjmNVDtC4vkbLCdXJQbVOUZuRoDFli7VKKf3aiVytJfqhZ8=,iv:ZkTl+tPhC/hqlCixZiMUgXlfFdo5DGcMwIHJ18gdyJg=,tag:mhYYrLea37WuVqdIaWMrDg==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: flux-system
sops:
    age:
        - recipient: age1744p6gzjcmysmyx4lmlmhre9sxqysp68er0ywwahgaqm8q98nd0s6r797v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTSzlad1Zjd3B6bHhrNU9L
            dWxFRjloMkExenNlZksrTXVUSktlczkraGljCmZ3QzFmMVpKV0Y3SzBpbWRxUUtU
            TjVsLzhuZWdTaEtEMjk2aXlFN1NuSlkKLS0tIHlSZGFQbkVuY0FJVS9iVGdlbW9z
            bXdxQmsrNDRBOFpDUlJWWU8wQUlOTk0KcUn99WQyjUp4qpxQHdY0cYrB07fBFx1K
            6mT8MxMOvvNHoaRHKnO4MWiARIfcWh8FcatyUwKvKcsca3Gx3YYS0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T18:32:23Z"
    mac: ENC[AES256_GCM,data:h1G6jnSVdiCgrs/OwnIbVimfF6gDkbELx8ce9hG2QfeQv65ozcmMzeqSQjkR7+FNGF0dv7/wjI3qYZm9Qf9CV3WgfDtGKNWe5V0Arm8weRV6AcP+Eowh3PyTpRnrbKgQgk4/bxRioQDCxsZuzovgV1j5IwcKAptqqINsYlgSlps=,iv:sqOvcE+wu9j2dgnxBbX7+VVKocm2gIfxA5LnqxkR88M=,tag:pDPMO5YGzdZrexSh/z17ZQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
