apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
type: Opaque
data:
  {{- if .Values.redis.password }}
  REDIS_PASSWORD: {{ .Values.redis.password | b64enc }}
  {{- end }}
  {{- if .Values.jwt.authExpiresIn }}
  JWT_AUTH_EXPIRES_IN: {{ .Values.jwt.authExpiresIn | b64enc }}
  {{- end }}
  {{- if .Values.jwt.authRefreshExpiresIn }}
  JWT_AUTH_REFRESH_EXPIRES_IN: {{ .Values.jwt.authRefreshExpiresIn | b64enc }}
  {{- end }}
  {{- if .Values.jwt.authRefreshSecret }}
  JWT_AUTH_REFRESH_SECRET: {{ .Values.jwt.authRefreshSecret | b64enc }}
  {{- end }}
  {{- if .Values.jwt.authSecret }}
  JWT_AUTH_SECRET: {{ .Values.jwt.authSecret | b64enc }}
  {{- end }}
  {{- if .Values.jwt.authVerificationExpiresIn }}
  JWT_AUTH_VERIFICATION_EXPIRES_IN: {{ .Values.jwt.authVerificationExpiresIn | b64enc }}
  {{- end }}
  {{- if .Values.jwt.authVerificationSecret }}
  JWT_AUTH_VERIFICATION_SECRET: {{ .Values.jwt.authVerificationSecret | b64enc }}
  {{- end }}
  {{- if .Values.emailService.username }}
  EMAIL_USERNAME: {{ .Values.emailService.username | b64enc }}
  {{- end }}
  {{- if .Values.emailService.password }}
  EMAIL_PASSWORD: {{ .Values.emailService.password | b64enc }}
  {{- end }}
  {{- if .Values.cookies.secret }}
  COOKIE_SECRET: {{ .Values.cookies.secret | b64enc }}
  {{- end }}
