apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
type: Opaque
data:
  REDIS_PASSWORD: {{ .Values.redis.password | quote | b64enc }}
  JWT_AUTH_EXPIRES_IN: {{ .Values.jwt.authExpiresIn | quote | b64enc }}
  JWT_AUTH_REFRESH_EXPIRES_IN: {{ .Values.jwt.authRefreshExpiresIn | quote | b64enc }}
  JWT_AUTH_REFRESH_SECRET: {{ .Values.jwt.authRefreshSecret | quote | b64enc }}
  JWT_AUTH_SECRET: {{ .Values.jwt.authSecret | quote | b64enc }}
  JWT_AUTH_VERIFICATION_EXPIRES_IN: {{ .Values.jwt.authVerificationExpiresIn | quote | b64enc }}
  JWT_AUTH_VERIFICATION_SECRET: {{ .Values.jwt.authVerificationSecret | quote | b64enc }}
  EMAIL_USERNAME: {{ .Values.emailService.username | quote | b64enc }}
  EMAIL_PASSWORD: {{ .Values.emailService.password | quote | b64enc }}
  COOKIE_SECRET: {{ .Values.cookies.secret | quote | b64enc }}
