apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  POSTGRESQL_HOST: {{ include "core-service.postgresql.host" . | quote }}
  POSTGRESQL_PORT: {{ include "core-service.postgresql.port" . | quote }}
  POSTGRESQL_DATABASE: {{ include "core-service.postgresql.database" . | quote }}

  REDIS_HOST: {{ .Values.redis.host | quote }}
  REDIS_PORT: {{ .Values.redis.port | quote }}

  KAFKA_HOST: {{ .Values.kafka.host | quote }}
  KAFKA_PORT: {{ .Values.kafka.port | quote }}
