apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ include "snippetquiz-core-service-chart.fullname" . }}
  name: {{ include "snippetquiz-core-service-chart.fullname" . }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ include "snippetquiz-core-service-chart.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "snippetquiz-core-service-chart.fullname" . }}
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - image: ghcr.io/rafaesc/snippetquiz/snippetquiz-core-service:{{ .Chart.AppVersion }}
          name: snippetquiz-core-service
          ports:
            - containerPort: 3003
          envFrom:
            - configMapRef:
                name: {{ include "snippetquiz-core-service-chart.fullname" . }}-config
            - secretRef:
                name: {{ include "snippetquiz-core-service-chart.fullname" . }}-secret
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ include "snippetquiz-core-service-chart.fullname" . }}
  name: {{ include "snippetquiz-core-service-chart.fullname" . }}
spec:
  selector:
    app: {{ include "snippetquiz-core-service-chart.fullname" . }}
  ports:
    - port: 3003
      targetPort: 3003