apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
type: Opaque
data:
  POSTGRESQL_USER: {{ .Values.postgresql.user | b64enc }}
  POSTGRESQL_PASSWORD: {{ .Values.postgresql.password | b64enc }}
  REDIS_PASSWORD: {{ .Values.redis.password | b64enc }}
