apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
type: Opaque
data:
  POSTGRESQL_USER: {{ include "core-service.postgresql.user" . | b64enc }}
  POSTGRESQL_PASSWORD: {{ include "core-service.postgresql.password" . | b64enc }}
  REDIS_PASSWORD: {{ .Values.redis.password | b64enc }}
