replicaCount: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

redis:
  host: redis
  port: "6379"
  password: snippetquiz

jwt:
  authExpiresIn: null
  authRefreshExpiresIn: null
  authRefreshSecret: null
  authSecret: null
  authVerificationExpiresIn: null
  authVerificationSecret: null

emailService:
  username: null
  password: null

routers:
  aiContentServiceHost: null
  authServiceHost: null
  coreServiceHost: null

cookies:
  secret: null