replicaCount: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

redis:
  host: redis
  port: "6379"
  password: snippetquiz

jwt:
  authExpiresIn: ""
  authRefreshExpiresIn: ""
  authRefreshSecret: ""
  authSecret: ""
  authVerificationExpiresIn: ""
  authVerificationSecret: ""

emailService:
  username: ""
  password: ""

routers:
  aiContentServiceHost: ""
  authServiceHost: ""
  coreServiceHost: ""

cookies:
  secret: ""