apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: snippetquiz-auth-service-chart
  namespace: flux-system
spec:
  interval: 5m
  url: oci://ghcr.io/rafaesc/snippetquiz-auth-service-chart
  secretRef:
    name: ghcr-secret
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: snippetquiz-auth-service-chart
  namespace: flux-system
spec:
  chartRef:
    kind: OCIRepository
    name: snippetquiz-auth-service-chart
    namespace: flux-system
  interval: 10m
  values:
    replicaCount: 1
