apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: snippetquiz-auth-service-chart
  namespace: snippetquiz
spec:
  interval: 5m
  url: oci://ghcr.io/rafaesc/charts/snippetquiz-auth-service-chart
  ref:
    tag: 0.0.18
  secretRef:
    name: ghcr-secret
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: snippetquiz-auth-service-chart
  namespace: snippetquiz
spec:
  chartRef:
    kind: OCIRepository
    name: snippetquiz-auth-service-chart
    namespace: snippetquiz
  interval: 10m
  values:
    replicaCount: 1
