apiVersion: v1
data:
    password: ENC[AES256_GCM,data:qhu/CBKQRKcRzK5a5oa6lA==,iv:okWsSSTqzHgiNoc7O0qtFV8IA1S6ykl96+pRFJFsg7s=,tag:t4oVwVVAkhrZBvo+hozaxg==,type:str]
kind: Secret
metadata:
    name: redis-sessions-password
    namespace: snippetquiz
sops:
    age:
        - recipient: age1744p6gzjcmysmyx4lmlmhre9sxqysp68er0ywwahgaqm8q98nd0s6r797v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnb1d5b0hJckhGQytJN2Fk
            SGw2aFIxRWFpbmphRHhueDh0RW5MQVViTndNCktQRk1kVklCd2ViSjBtNVBORVY5
            eVY5VUhsWEtrVGVEdHpPdjZaQzBFUkkKLS0tIDNka0tVOWM3STdQOTk2NVR3WjZH
            a2tSWkg1OU56NnI4a1Vobzh1enhOZTgKRibNSIehiIwDsw8BaWRwAISsthEzDNKp
            dws9BKly3zL5tOYg1xC2rCTL1eq20Lscc+dF4+5l8QT/KVR1yjH97Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T03:18:20Z"
    mac: ENC[AES256_GCM,data:32lPUTKACesKmuTirvAY5LVB/vIIDeu9VwajJx64JSjGt3wjZpKwdNbuPtXT7fDEU2c7Z+9klj9wTPbvP2sDmsAnegibH8orBreFj706OuVNeW/J0MCmJSzaggdKXlv6UADALKLMgqysQDWzJBKEFBNpiVEVrGc9Knze5XYHRIs=,iv:4zbq1k7OqiYujQG1wB87+0Rklp/7MrQxZOB5Wq0bIpI=,tag:cHnJaYvIEeh89GX91V1xDA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
