apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: strimzi-kafka-operator
  namespace: snippetquiz
spec:
  interval: 30m
  chart:
    spec:
      chart: strimzi-kafka-operator
      version: "0.49.1"
      sourceRef:
        kind: HelmRepository
        name: strimzi
        namespace: snippetquiz
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    dashboards:
      enabled: false
