apiVersion: v1
kind: Secret
metadata:
  name: common-env
  namespace: snippetquiz
type: Opaque
stringData:
  AI_CONTENT_SERVICE_HOST: ""
  API_BASE_URL: ""
  AUTH_SERVICE_HOST: ""
  COOKIE_SECRET: ""
  CORE_SERVICE_HOST: ""
  EMAIL_PASSWORD: ""
  EMAIL_USERNAME: ""
  JWT_AUTH_EXPIRES_IN: ""
  JWT_AUTH_REFRESH_EXPIRES_IN: ""
  JWT_AUTH_REFRESH_SECRET: ""
  JWT_AUTH_SECRET: ""
  JWT_AUTH_VERIFICATION_EXPIRES_IN: ""
  JWT_AUTH_VERIFICATION_SECRET: ""
  KAFKA_HOST: ""
  KAFKA_PORT: ""
  OPENROUTER_API_KEY: ""
  POSTGRESQL_DATABASE: ""
  POSTGRESQL_HOST: ""
  POSTGRESQL_PASSWORD: ""
  POSTGRESQL_PORT: ""
  POSTGRESQL_USER: ""
  REDIS_HOST: ""
  REDIS_PASSWORD: ""
  REDIS_PORT: ""
