apiVersion: v1
data:
    api-token: ENC[AES256_GCM,data:P2OrDsf61EwOuz95hD+6RN8Xh3IdtvbB4ZTwqi9dpWVFiBFCsVZbzkTu3AVyFjjU9R9VHvhm6tA=,iv:eQywNlZpzC2Je/UFy91pMviv85pgzQSH4pXSXJwwDhM=,tag:eLZedUk8meCJtZ0CDka4Fg==,type:str]
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
sops:
    age:
        - recipient: age1744p6gzjcmysmyx4lmlmhre9sxqysp68er0ywwahgaqm8q98nd0s6r797v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRNTBRQ3pvdEhqeURiQy9n
            MUk1Z0N2bi9jcHQyTDQyRC9maUdsNmpWS1I4Cm9uZDNCNnBtQkFOYlJyRXVqbzhY
            anZ6RzFDc0hFN0dVcS9tSjB0YU5LUEUKLS0tIHNJWHZ6dzZaeHFGODRwSnV4QWdZ
            KzEzTEJEQ3QvWlV4R3pFbUUrb2h3VkUKs8S4CBZQUZIsInzz8O6NPeZgr7IfBu75
            BUAhLzzCD/B+cW6IUQYbX6cEEYUBYx2wZTDYkKPlCVpcopjDaJR39A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-03T00:56:26Z"
    mac: ENC[AES256_GCM,data:uZcPipBZeI5Pi9Bgs1Zte8DSiD5LCFWHbPxHIqjo3dhGu7Mp78/cn+EMx0Zr3iCAYTTmrc+Jme+FBO+oTGhl7vT0k2JOl6LIlYV6GYekiSADhCj8Qo0LBprVikSRfJ5kEA5m2fpmXOqTa8aZkerwvI/DrSi6QNUAwHNKUoq8iKQ=,iv:xlZHsjX2Tpd2589seYRIooZXPLny4fLmnW6H40awilQ=,tag:mSFiMWISxsFehxWQ3+FydA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
