apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: snippetquiz
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:rhjwDWOn+Jm7WneefECg7zWPQjB03Ilb/JgkJEQnKqV/Jyc+9HRPiN9E/m5axqjYzSNr977OGRk=,iv:mIzGlbZ76I2M5UbTMHOe3/+co4tMewPgEKqUJm8bUho=,tag:y7yCFDrHUoskmuKy9pAg0A==,type:str]
sops:
    age:
        - recipient: age1744p6gzjcmysmyx4lmlmhre9sxqysp68er0ywwahgaqm8q98nd0s6r797v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmWHFkWHFIT01iQzArRnE0
            YmE5eFhpazRTc0wxRm9LYW13Z0lqWmhobjA4ClA0RzdDb05FSjZWUVd4SzFLdk91
            NFZpU1BsTlQwT1VnZ3BLZnV4VGxMY00KLS0tIHdKd2xjZmxCTjZUVnVQeFJQNlBo
            S0R6R1JOUUJ2UjhrWEdYdFJTb2VsNGsKTE6CzZkoBZ7A4lhwvzkOdD3FEZrXLDKm
            jozR8VhJhviSIYIzbNFSF6AMPN+ycfsC/bYxYPn43ES6xwYMZtxZ7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-02T06:06:10Z"
    mac: ENC[AES256_GCM,data:dPwg+yvnoL0DJb50Q5yHFKemOAhQ5fNaGAEFv8LL84lqaSTQEaAVH2J7j+cqkeGJSIFfFf0tdsaOdkohwXHKTxPQaCT9X2Kkab9vUPk6622IUZfhJMxZZo3hSLiejRr3yMJ8ziHsZGqBGP1xl4qju2pTPqVu3c5a+MhkieVPTeU=,iv:4uP3Uhz35Oi3LXKQ2mxWZ6zQF07dq8IPPuJiaZi9gnM=,tag:DBWbdmGYCOCCgGwCszpDjg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
