name: Publish Docker images
on: 
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{secrets.PACKAGE_TOKEN}}

      - name: Build and push API Gateway
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/apps/api-gateway/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/snippetquiz-api-gateway:latest

      - name: Build and push Auth Service
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/apps/auth-service/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/snippetquiz-auth-service:latest

      - name: Build and push Core Service
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/apps/core-service/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/snippetquiz-core-service:latest

      - name: Build and push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ghcr.io/${{ github.repository }}/snippetquiz-frontend:latest
