name: Publish Docker images
on: 
  push:
    paths:
      - 'backend/**'
      - 'frontend/**'
    branches:
      - master

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      java: ${{ steps.filter.outputs.java }}
      nestjs: ${{ steps.filter.outputs.nestjs }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            java:
              - 'backend/java/**'
            nestjs:
              - 'backend/nestjs/**'
            frontend:
              - 'frontend/**'

  build-and-push:
    needs: changes
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      API_URL: http://localhost:5000
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{secrets.PACKAGE_TOKEN}}

      - name: Setup Node.js for NestJS
        if: ${{ needs.changes.outputs.nestjs == 'true' }}
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: backend/nestjs/package-lock.json

      - name: Install NestJS dependencies
        if: ${{ needs.changes.outputs.nestjs == 'true' }}
        run: npm ci
        working-directory: ./backend/nestjs

      - name: Build NestJS Apps
        if: ${{ needs.changes.outputs.nestjs == 'true' }}
        run: |
          npm run prisma:generate:auth
          npm run prisma:generate:ai-processor
          npx nest build api-gateway
          npx nest build auth-service
          npx nest build ai-processor
        working-directory: ./backend/nestjs

      - name: Build and push API Gateway
        if: ${{ needs.changes.outputs.nestjs == 'true' }}
        uses: docker/build-push-action@v5
        with:
          context: ./backend/nestjs
          file: ./backend/nestjs/apps/api-gateway/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/snippetquiz-api-gateway:latest

      - name: Build and push Auth Service
        if: ${{ needs.changes.outputs.nestjs == 'true' }}
        uses: docker/build-push-action@v5
        with:
          context: ./backend/nestjs
          file: ./backend/nestjs/apps/auth-service/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/snippetquiz-auth-service:latest

      - name: Build and push AI Processor Service
        if: ${{ needs.changes.outputs.nestjs == 'true' }}
        uses: docker/build-push-action@v5
        with:
          context: ./backend/nestjs
          file: ./backend/nestjs/apps/ai-processor/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/snippetquiz-ai-processor:latest

      - name: Setup Java
        if: ${{ needs.changes.outputs.java == 'true' }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Java Service
        if: ${{ needs.changes.outputs.java == 'true' }}
        run: ./gradlew build
        working-directory: ./backend/java

      - name: Build and push Core Service
        if: ${{ needs.changes.outputs.java == 'true' }}
        uses: docker/build-push-action@v5
        with:
          context: ./backend/java
          file: ./backend/java/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/snippetquiz-core-service:latest

      - name: Setup Node.js
        if: ${{ needs.changes.outputs.frontend == 'true' }}
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        if: ${{ needs.changes.outputs.frontend == 'true' }}
        run: npm ci
        working-directory: ./frontend

      - name: Build Frontend
        if: ${{ needs.changes.outputs.frontend == 'true' }}
        run: npm run build
        working-directory: ./frontend

      - name: Build and push Frontend
        if: ${{ needs.changes.outputs.frontend == 'true' }}
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          build-args: |
            API_URL=http://localhost:5000
          push: true
          tags: ghcr.io/${{ github.repository }}/snippetquiz-frontend:latest
