name: Publish Docker images
on: 
  push:
    paths:
      - 'backend/**'
      - 'frontend/**'
    branches:
      - master

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      java: ${{ steps.filter.outputs.java }}
      nestjs: ${{ steps.filter.outputs.nestjs }}
      python: ${{ steps.filter.outputs.python }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            java:
              - 'backend/java/**'
            nestjs:
              - 'backend/nestjs/**'
            python:
              - 'backend/python/**'
            frontend:
              - 'frontend/**'

  build-and-push:
    needs: changes
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{secrets.PACKAGE_TOKEN}}

      - name: Build and push API Gateway
        if: ${{ needs.changes.outputs.nestjs == 'true' }}
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/nestjs/apps/api-gateway/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/snippetquiz-api-gateway:latest

      - name: Build and push Auth Service
        if: ${{ needs.changes.outputs.nestjs == 'true' }}
        uses: docker/build-push-action@v5
        with:
          context: ./backend/nestjs
          file: ./backend/nestjs/apps/auth-service/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/snippetquiz-auth-service:latest

      - name: Build and push Core Service
        if: ${{ needs.changes.outputs.java == 'true' }}
        uses: docker/build-push-action@v5
        with:
          context: ./backend/java
          file: ./backend/java/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/snippetquiz-core-service:latest

      - name: Build and push AI Python Service
        if: ${{ needs.changes.outputs.python == 'true' }}
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/python/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/snippetquiz-ai-python-service:latest

      - name: Build and push Frontend
        if: ${{ needs.changes.outputs.frontend == 'true' }}
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          build-args: |
            API_URL=http://localhost:5000
          push: true
          tags: ghcr.io/${{ github.repository }}/snippetquiz-frontend:latest
